platform :ios, '7.0'
pod 'AFNetworking', '~>2.6.0'
pod 'ReactiveCocoa', '~> 2.5'
pod 'SDWebImage', '~> 3.7.5'
pod 'JSONModel', '~> 1.0.1'
pod 'Masonry','~>0.6.1'
pod 'FMDB/common' , '~>2.5'
pod 'FMDB/SQLCipher', '~>2.5'
pod 'CocoaLumberjack', '~> 2.0.0-rc'
pod 'BaiduMapKit' 
pod 'UMengAnalytics-NO-IDFA'
pod 'GTSDK'  
pod 'UMengSocial', '~> 4.3'  
pod 'FLEX', '~> 2.0'
pod 'ActionSheetPicker-3.0'
pod 'JSPatch'
pod 'XAspect'
pod 'CYLTabBarController'
pod 'LKDBHelper'
pod 'RegexKitLite', '4.0'
pod 'IQKeyboardManager'
pod 'LBXScan','~> 1.1.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'MWPhotoBrowser'
pod 'M13ProgressSuite', '~> 1.2.7'
pod 'WebViewJavascriptBridge', '~> 5.0'
pod 'YYText'
